// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdbuwyzfinlbyflcrkwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYnV3eXpmaW5sYnlmbGNya3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTc1MDgsImV4cCI6MjA2MzIzMzUwOH0.bRNCcgim1mlBHhQs-q21wJNO4EeSsuYWhAswCr2E6l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);